spring:
  sql:
    init:
      mode: always
      separator: ';;'
  datasource:
    url: jdbc:postgresql://localhost:5432/hanchengzhe
    username: hanchengzhe
    password: 810918zhuzhu
    driver-class-name: org.postgresql.Driver
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.example.blogx.post,com.example.blogx.user
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8080
  servlet:
    context-path: /
springdoc:
  api-docs:
    enabled: false
